spring:
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret:
    key: ${jwt.secret.key}
  access:
    expire: ${jwt.access.expire}
  refresh:
    expire: ${jwt.refresh.expire}

    
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

